server:
  port: 8080
spring:
  application:
    name: "technology"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: school_technology
    username: postgres
    password: postgres
    schema: public
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
# En tu application.yaml, agrega temporalmente:
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# JWT Configuration
jwt:
  secret: "VQasauJliIvkAJIc29suAFYpKItz7jkinzImfhSxCD4="
  audience: "pragma-user-service"
  issuer: "pragma-auth-service"
  expiration: 86400 # 1 hora en segundos

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

swagger:
  title: "Technology Service API"
  description: "API documentation for the Technology Service"
  version: "1.0.0"
  urlServer: "http://localhost:8080"
